### ISSUE TITLE
Crash in Defcon28 release noctilucent-cloak-client-windows.exe when passing traffic

### ISSUE THREAD

**Issue by bryan-buckman** [SixGenInc/Noctilucent#1]
Hi Erik,

I'm getting a crash and Go stack trace when using the precompiled Cloak client for windows.  It listens fine until traffic is passed through it from shadowsocks, then fails immediately.  Win10 Pro - 19041.  I haven't tried compiling the latest from source yet.  Please let me know if you need the config file also, but it's essentially identical to your sample except for the local port and keys, etc.:

```
PS C:\tools> .\noctilucent-cloak-client-windows.exe -c ckclient.json
time="2020-08-07T23:30:09-05:00" level=info msg="Starting standalone mode"
time="2020-08-07T23:30:09-05:00" level=info msg="Listening on TCP 127.0.0.1:8088 for shadowsocks client"
time="2020-08-07T23:30:23-05:00" level=info msg="Attempting to start a new session"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x8 pc=0x6870e9]

goroutine 6 [running]:
github.com/cbeuw/Cloak/internal/common.(*WebSocketConn).Close(0x0, 0x0, 0x0)
        /Users/erik/Documents/DC28/final_work/Cloak/internal/common/websocket.go:61 +0x49
github.com/cbeuw/Cloak/internal/client.MakeSession.func1(0x7beae0, 0xc00001c300, 0x4, 0xffffffffffffffff, 0xc00000e6e0, 0x12, 0xc000004900, 0xc000110230, 0xc0000470b0, 0xc00001c360, ...)
        /Users/erik/Documents/DC28/final_work/Cloak/internal/client/connector.go:52 +0x2da
created by github.com/cbeuw/Cloak/internal/client.MakeSession
        /Users/erik/Documents/DC28/final_work/Cloak/internal/client/connector.go:39 +0x21d
```

**Comment by SixGenInc** [comment]
This happens when the websocket handshake fails. In testing this occurs when your Cloudflare SSL/TLS settings are not set to "Flexible" and your Cloak server is listening on port 80. I've added a fatal error with a helpful message instead of letting this panic happen. The release binaries are updated as well. Let me know if you still have issues.

**Comment by bryan-buckman** [comment]
That helped, thank you.

For anyone having a similar issue, for me specifically this was a PEBKAC... may help to note that you need both 80 and 443 open between Cloudflare and your server.
